### PR TITLE
add archive only mode

### PR DESCRIPTION
**Pull request by hellodword**
... so we can do web archiving to a single html like obelisk (I know the internal/obelisk is like a fork, but the upstream had been dead for years https://github.com/go-shiori/obelisk/issues/2)

```sh
rivet -m archive https://mp.weixin.qq.com/s/wa98LIcSmoRz-1LxAfWZ9w

# mp-weixin-qq-com-s-wa98LIcSmoRz-1LxAfWZ9w.html  https://mp.weixin.qq.com/s/wa98LIcSmoRz-1LxAfWZ9w
```

### CODE REVIEW

**Comment by hellodword** [comment]
And I think you can really fork the obelisk and continue it as a tool/package.

**Comment by waybackarchiver** [comment]
> And I think you can really fork the obelisk and continue it as a tool/package.

Sure, the next step will be to consider merging the changes from [internal/obelisk](https://github.com/wabarc/rivet/tree/ed329cb9369c70e48cac6852cb276db830229f52/internal/obelisk) to [wabarc/obelisk](/wabarc/obelisk).

**Comment by waybackarchiver** [comment]
@hellodword #2, #3, #5, #6 merged into https://github.com/wabarc/obelisk/compare/3b6ce1f...8b436c6

**Comment by waybackarchiver** [comment]
Related: https://github.com/wabarc/obelisk/commit/cf6b1b2fa65d04cccbf0a3f1f7502324489f97f4

**Pull request merged**
